class TagError(Exception): ...
class SettingDoesNotExist(Exception): ...
class ScriptInjectionIsNotAllowed(Exception): ...
class IndentifierDoesNotExist(Exception): ...
class ArgumentNotAllowed(Exception): ...
class UsageIsNotAllowed(Exception): ...